branches:
    except:
        - gh-pages

environment:
    QTDIR: C:\Qt\6.5.3\mingw_64
    MINGW_DIR: C:\Qt\Tools\mingw1120_64

install:
    - set PATH=%QTDIR%\bin;%MINGW_DIR%\bin;%PATH%
    - git submodule update --init --recursive

before_build:
    - mkdir build
    - cd build
    - qmake ..\CuteMarkEd.pro

build_script:
    - mingw32-make

test_script:
    - cd test\unit
    - mingw32-make check
